# dtb recompiler
# TG: @mochi_wwww / GIT: Jebaitedneko
MATCH="Qualcomm Technologies, Inc. SM8150 v2 SoC"
[ ! -f boot.img ] && echo -e "Run\n\n\nsu\n\nsh img.sh\n\nexit\n\n\nand then re-run run-dtb.sh"  && exit
./extract-dtb.sh "boot.img" "$MATCH"
cp dts dts.old
label() {
	sed -i "s/$1 {/$2: $1 {/g" "dts"
}
label "soc" "soc"
label "gpu_opp_table_v2" "gpu_opp"
label "qcom,gpu-pwrlevels-1" "gpu_pwrlvl"
label "lmh-dcvs-00" "lmh_0"
label "lmh-dcvs-01" "lmh_1"
cat "dtb.dtsi" >> "dts"
sed -i "s/==> dts <==//g" "dts"
$DTC -I dts -O dtb "dts" -o "dtb" && rm "dts"
$DTC -I dtb -O dts -o dts.new "dtb"
echo "Done."
echo -e "\nAutogenerated from dtb-recompiler\nby MOCHI [TG: @mochi_wwww | GIT: @Jebaitedneko]\n" >> banner
echo -e "$(diff -ur dts.old dts.new)" >> banner && rm dts.old dts.new
cat dtb.dtsi >> banner