# dtb recompiler
# TG: @mochi_wwww / GIT: Jebaitedneko
MATCH="VAYU"
[ ! -f dtbo-stock.img ] && echo -e "Run\n\n\nsu\n\nsh img.sh\n\nexit\n\n\nand then re-run run-dtbo.sh" && exit

if [ $(env | grep ANDROID_DATA | wc -c) -gt 0 ]; then
    export MAGISKBOOT="$(pwd)/tools/magiskboot"
    export MKDTIMG="$(pwd)/mkdtimg-aarch64"
    export DTC="$(pwd)/dtc-aarch64 -q"
else
    export MAGISKBOOT="$(pwd)/magiskboot-x86"
    export MKDTIMG="$(pwd)/mkdtimg-x86"
    export DTC="$(which dtc) -q"
fi

dir_check() {
    [ -d dtbs ] && rm -rf dtbs; mkdir dtbs || mkdir dtbs
}

common() {
    ( cd dtbs; ls -1 * | while read f; do $DTC -q -I dtb -O dts "$f" -o $(echo "$f" | sed -E "s/.dtb//g;s/dtbos.([0-9]+)/\1/g").dts; done; rm *dtb* )
    mv "$(grep -r "$2" -l dtbs)" "./dts" && rm -rf dtbs
}

unpack_dtbo() {
    dir_check
    $MKDTIMG dump "$1" -b dtbos &> /dev/null
    [ -f dtbos.0 ] && mv dtbos* dtbs
    common "$1" "$2"
}

unpack_dtbo "dtbo-stock.img" "$MATCH"
cp dts dts.old

label() {
	sed -i "s/$1 {/$2: $1 {/g" "dts"
}

echo -e "\n" >> dts

get_frag_num() {
	FRAG_NUM=$(grep -B4 $1 dts | tail -n5 | head -n1 | grep -oE '[0-9]+')
}

TEMPLATE="
__local_fixups__ {
	fragment@FRAG_NUM {
		__overlay__ {
			NODE_NAME {
				PROP;
			};
		};
	};
};
"

push_node() {
	get_frag_num $1
	FIXUP=$(echo $TEMPLATE | sed "s/FRAG_NUM/$FRAG_NUM/g;s/NODE_NAME/$1/g;s/PROP/$(echo -e $2)/g")
	echo -e "/ { $FIXUP };" >> dts
}

push_node "qcom,mdss_dsi_j20s_36_02_0a_dsc_video" '
	qcom,esd-check-enabled;
	qcom,mdss-dsi-panel-status-check-mode = "reg_read";
	qcom,mdss-dsi-panel-status-command = [06 01 00 01 00 00 01 0a];
	qcom,mdss-dsi-panel-status-command-state = "dsi_lp_mode";
	qcom,mdss-dsi-panel-status-value = <0x9c>;
	qcom,mdss-dsi-panel-status-read-length = <1>;
'

push_node "qcom,mdss_dsi_j20s_42_02_0b_dsc_video" '
	qcom,esd-check-enabled;
	qcom,mdss-dsi-panel-status-check-mode = "reg_read";
	qcom,mdss-dsi-panel-status-command = [06 01 00 01 00 00 01 0a];
	qcom,mdss-dsi-panel-status-command-state = "dsi_lp_mode";
	qcom,mdss-dsi-panel-status-value = <0x9c>;
	qcom,mdss-dsi-panel-status-read-length = <1>;
'

sed -i "s/;;/;/g" "dts"
$DTC -I dts -O dtb -o "dtb" "dts"
$DTC -I dtb -O dts -o "dts.new" "dtb"
echo "Done."
echo -e "\nAutogenerated from dtbo-recompiler\nby MOCHI [TG: @mochi_wwww | GIT: @Jebaitedneko]\n" >> banner
echo -e "$(diff -ur dts.old dts.new)" >> banner && rm dts.old dts.new dts
$MKDTIMG create dtbo.img --page_size=4096 dtb